### PR TITLE
Add support for prologue/epilogue

### PR DESCRIPTION
**Pull request by leonardt**
Feature request from @phanrahan to allow the user to extend the
apply_passes behavior by adding logic before and/or after passes are
run.

### CODE REVIEW

**Comment by phanrahan** [comment]
Looks great. Thank you!

**Comment by cdonovick** [comment]
Looks fine to me but I am curious what the use case is.  Why not perform prologue / epilogue in a pass it self?

**Review by cdonovick — APPROVED** [review]

**Comment by phanrahan** [comment]
I requested this feature for my experimental implementation of magma. I want to formalize it by defining an algebraic data type and writing multiple interpreters of that datatype. The AST stands in as the algebraic data type. This allows me easy access to the AST.

**Comment by cdonovick** [comment]
@phanrahan I am still unclear why a pass won't achieve what you want.

To be clear I have no problem with this PR, I just want to understand what limitations of the pass architecture are causing you problems.  My confusion stems from the fact that a `Pass.rewrite` has the same type signature as prologue / epilogue . Is the issue that you need prologue / epilogue to communicate with each other or exec in some way that isn't elegant in the current architecture?

**Comment by phanrahan** [comment]
I want to get access to the AST produced after the passes are run. This is the way Lenny recommended. I am open to anything!

**Comment by cdonovick** [comment]
The way I would write this is:

```Python
@apply_passes([prologue, *passes, epilogue])
```

But again if what ever reason this is not ergonomic I am happy with this pr.

**Comment by phanrahan** [comment]
I want to do something like this

`tree, env, metadata = apply_passes(function, pass1, pass2) `

**Comment by cdonovick** [comment]
Okay, that makes more sense.  I am also not sure if this PR fixes this for you.  I would recommend the following solution:

```Python
class apply_passes_no_exec(apply_passes):
    def exec(self, etree, stree, env, metadata):
          # depending on what your plans are you should either return etree or stree
          return etree, env, metadata

tree, env, metadata = apply_passes_no_exec([passes])(function)
```

We serialize stree and exec etree.  The explanation of why these are different is somewhat involved and is documented in #46. Most likely you will want etree.

**Comment by cdonovick** [comment]
Or I guess thinking about it now this solution actually does work if you do the following:

```Python
class apply_passes_save_tree(apply_passes):
    def epilogue(self, tree, env, metadata):
        self.tree = tree


deco = apply_passes_save_tree([passes])
rewritten_function = deco(function)
tree = deco.tree
```

**Comment by cdonovick** [comment]
Actually I am going back to this doesn't really acheive much.  I think I would write this code like:
```Python
class SaveTree(Pass):
    def rewrite(self, tree, env, meta):
        # could save tree in a global if you are into that sort of thing
        self.tree = tree
        return tree, env, meta

save_tree = SaveTree()
# or alternatively called as a normal function
@apply_passes([*passes, save_tree])
def function(...): ...

tree = save_tree.tree
```

**Comment by phanrahan** [comment]
I like that solution!

**Comment by rsetaluri** [comment]
> Actually I am going back to this doesn't really acheive much. I think I would write this code like:
> 
> ```python
> class SaveTree(Pass):
>     def rewrite(self, tree, env, meta):
>         # could save tree in a global if you are into that sort of thing
>         self.tree = tree
>         return tree, env, meta
> 
> save_tree = SaveTree()
> # or alternatively called as a normal function
> @apply_passes([*passes, save_tree])
> def function(...): ...
> 
> tree = save_tree.tree
> ```


Agree this is nicer and more general. This allows you to get the tree in before/after any pass. (Could even add a function like `make_saver = lambda p: chain(p, SaveTree())`)

As a nicety to avoid having to instantiate `save_tree = SaveTree()` in a floating context, you could attach all passes and expose them:

```
def get_passes(fn):
    return getattr(fn, "_ast_passes_", list())
    
 ...
@apply_passes([*passes, SaveTree()])
def function(): ...

tree = ast_tools.get_passes(function)[-1]
```

(with the obvious downside now that even ephemeral passes won't get garbage collected...)

**Comment by leonardt** [comment]
To add some context, one of the original simple ideas we discussed over email was to define a subclass of apply_passes that appends a final pass, this is similar to caleb's most recent suggestion

```
> class final_pass(Pass):
>     def rewrite(self, tree, env, metadata):
>         print("Final CST")
>         print(tree)
>         return tree, env, metadata
>
>
> class apply_passes_with_final_pass(apply_passes):
>     def __init__(self, passes, *args, **kwargs):
>         super().__init__(passes + [final_pass()], *args, **kwargs)
```

The nice thing about using a class rather than a pass is that we can wrap this in some reusable container, rather than having to provide the pass at every call site.  A "decorator wrapper" would work too (one that appends the pass), but I think the subclass/override approach provides a more natural way to handle extending this logic (i.e. if we defined a wrapper function that class apply_passes internally with the pass appended, we can't subclass quite as easily as an approach using a class pipeline).

However, I think the use case here is pretty simple so I don't know if we need to spend too much time bike shedding on the "right" way to do this.  As shown, there are quite a few ways to achieve the goal without needing to modify the internal code, which is always a good thing.  As a counterpoint, I think the refactoring here of "prologue", "do_passes", "epilogue" seems like a sane pattern that could be useful in unexpected ways down the line with little cost in code complexity.  I could imagine generally that users may want to add arbitrary logic before and after passes.  This logic doesn't necessarily need to be a pass (although it has access to the pass arguments).  For example, down the line we might choose to add some abstract methods for passes that some prologue/epilogue logic would not necessarily need to provide.

**Comment by cdonovick** [comment]
> The nice thing about using a class rather than a pass is that we can wrap this in some reusable container, rather than having to provide the pass at every call site.

Hmmm, this is reasonable. 

> As a counterpoint, I think the refactoring here of "prologue", "do_passes", "epilogue" seems like a sane pattern that could be useful in unexpected ways down the line with little cost in code complexity.

I am fine with merging this.

**Comment by cdonovick** [comment]
Also I  just realized the behavior that @phanrahan  wants is actually already supported.  see: https://github.com/leonardt/ast_tools/blob/master/ast_tools/passes/util.py#L231

so one could get the rewritten tree prior to decorator stripping (see: https://github.com/leonardt/ast_tools#wrapping-the-apply_passes-decorator) with:

```
deco = apply_passes(passes)

@deco
def function(...): ...

deco.f_tree
```

**Pull request merged**
